#!/bin/bash

### BEGIN INIT INFO
# Provides: h2o
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop h2o
# Description: so fresh
### END INIT INFO

INSTDIR=/usr/local/bin
PIDFILE=/var/run/h2o.pid
APP=h2o

case $1 in
  start)
    if [ -f $PIDFILE ]; then
      echo "err: $PIDFILE already exists"
      exit 1
    fi
    $INSTDIR/$APP -m daemon -c /etc/h2o/h2o.conf
    exit 0
    ;;
  stop)
    if [ -f "/var/run/h2o.pid" ]; then
      kill -TERM `cat /var/run/h2o.pid`
      echo stopping h2o...
    else
      echo stopped already
    fi
    exit 0
    ;;
  status)
    if [ -f "/var/run/h2o.pid" ]; then
      echo running with PID "`cat /var/run/h2o.pid`"
    else
      echo stopped
    fi
    exit 0
    ;;
  restart)
    $0 stop && $0 start
    ;;
  force-reload)
    $0 restart
    ;;
  *)
    echo "Argument \"$1\" not implemented."
    exit 2
    ;;
esac
